{% set name = "pyzotero" %}
{% set version = "1.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a6765b8d4ad4a7aa5ab4eda8c4d397bc035cd24ca32642b4a8d5fa80bb8178e5

build:
  noarch: python
  number: 0
  script:
    - rm -f pyproject.toml
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=45
    - setuptools-scm >=6.2
  run:
    - python >={{ python_min }}
    - feedparser >=6.0.11
    - pytz
    - requests >=2.21.0
    - bibtexparser
    - httpx >=0.28.1

test:
  imports:
    - pyzotero.zotero

about:
  home: https://github.com/urschrei/pyzotero
  license: BlueOak-1.0.0
  license_file: LICENSE.md
  summary: Python wrapper for the Zotero API
  doc_url: http://pyzotero.readthedocs.org
  dev_url: https://github.com/urschrei/pyzotero

extra:
  recipe-maintainers:
    - moorepants
    - urschrei
