{% set name = "pyzotero" %}
{% set version = "1.15.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9affddd556ccfff88187fa0340ed3b36cb995ec3d1add5d697ae089b1f4ceaf2

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - uv-build >=0.8.14
  run:
    - bibtexparser >=1.4.3
    - click >=8.0.0
    - feedparser >=6.0.12
    - httpx2 >=2.12.0
    - python >={{ python_min }}
    - whenever >=0.8.8
test:
  requires:
    - python {{ python_min }}
  imports:
    - pyzotero.zotero

about:
  home: https://github.com/urschrei/pyzotero
  license: BlueOak-1.0.0
  license_file: LICENSE.md
  summary: Python wrapper for the Zotero API
  doc_url: http://pyzotero.readthedocs.org
  dev_url: https://github.com/urschrei/pyzotero

extra:
  recipe-maintainers:
    - moorepants
    - urschrei
