{% set name = "pyzotero" %}
{% set version = "1.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: afdd79612b5e013ab9931f8b2a1419e36b2d52ece0b1711c9778e85f493e1e83

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - uv-build >=0.8.14
  run:
    - python >={{ python_min }}
    - feedparser >=6.0.12
    - bibtexparser >=1.4.3
    - httpx >=0.29.1
    - whenever >=0.8.8
    - click >=8.0.0
test:
  requires:
    - python {{ python_min }}
  imports:
    - pyzotero.zotero

about:
  home: https://github.com/urschrei/pyzotero
  license: BlueOak-1.0.0
  license_file: LICENSE.md
  summary: Python wrapper for the Zotero API
  doc_url: http://pyzotero.readthedocs.org
  dev_url: https://github.com/urschrei/pyzotero

extra:
  recipe-maintainers:
    - moorepants
    - urschrei
