{% set name = "pyzotero" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bc6b4b5ef34bb8b60ccf5be547b1c971e1a17792cc1b89bf84d5954d1dd7143b

build:
  noarch: python
  number: 0
  script:
    - rm -f pyproject.toml
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools-scm
  run:
    - python >=3.8
    - feedparser >=6.0.11
    - pytz
    - requests >=2.21.0
    - bibtexparser

test:
  imports:
    - pyzotero.zotero

about:
  home: https://github.com/urschrei/pyzotero
  license: BlueOak-1.0.0
  license_file: LICENSE.md
  summary: Python wrapper for the Zotero API
  doc_url: http://pyzotero.readthedocs.org
  dev_url: https://github.com/urschrei/pyzotero

extra:
  recipe-maintainers:
    - moorepants
    - urschrei
